spring.application.name=PersonalLibraryTracker

# MySQL settings
spring.datasource.url=jdbc:mysql://localhost:3306/library_tracker
spring.datasource.username=noc-sil
spring.datasource.password=mypassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Enviroment
BOOKS_API_KEY=${BOOKS_API_KEY}

# User Service Responses
Service.USER_NOT_FOUND=User not found
Service.USER_ALREADY_EXISTS=User already exists
Service.BOOK_NOT_FOUND_FOR_USER=Book not found for user
Service.PAGE_NUMBER_GOING_BACKWARDS=Page number cannot be less than or equal to last logged page number.
Service.PAGE_NUMBER_GOING_FORWARDS=Page number cannot be more than or equal to next logged page number.
Service.PAGE_NUMBER_EXCEEDS_BOOK=Page number cannot be more than the number of pages in the book.
Service.READING_SESSION_NOT_FOUND=Reading session not found for the given ID.
Service.NOTE_NOT_FOUND=No note found for the given ID.
Service.EMPTY_NOTE_CONTENT=Content should not be empty.
Service.REVIEW_ALREADY_EXISTS=Review already exists for the book. Please update it.
# User API Response Message
API.USER_FOUND_SUCCESS=User details found