spring.application.name=PersonalLibraryTracker

# MySQL settings
spring.datasource.url=${DB_LOCATION}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
# Environment
BOOKS_API_KEY=${BOOKS_API_KEY}
# User Service Responses
Service.USER_NOT_FOUND=User not found
Service.USER_ALREADY_EXISTS=User already exists
Service.BOOK_NOT_FOUND_FOR_USER=Book not found for user
Service.PAGE_NUMBER_GOING_BACKWARDS=Page number cannot be less than or equal to last logged page number
Service.PAGE_NUMBER_GOING_FORWARDS=Page number cannot be more than or equal to next logged page number
Service.PAGE_NUMBER_EXCEEDS_BOOK=Page number cannot be more than the number of pages in the book
Service.READING_SESSION_NOT_FOUND=Reading session not found for the given ID
Service.NOTE_NOT_FOUND=No note found for the given ID
Service.EMPTY_NOTE_CONTENT=Content should not be empty
Service.REVIEW_ALREADY_EXISTS=Review already exists for the book. Please update it
Service.REVIEW_NOT_FOUND_FOR_BOOK=Review not found for the book
Service.UNABLE_TO_SEARCH_BOOK=Unable to search book
Service.INVALID_CREDENTIALS=Invalid Credentials
Service.INVALID_REFRESH_TOKEN=Invalid token, please log in again
EXCEPTIONS.CONFLICT_DATABASE_EXCEPTION=Conflict with database
EXCEPTIONS.MALFORMED_HTTP_REQUEST_EXCEPTION=The request body is missing or malformed
EXCEPTIONS.SERVER_ERROR_EXCEPTION=Server error occurred
EXCEPTIONS.INVALID_CREDENTIALS=Invalid email or password.
EXCEPTIONS.INVALID_REFRESH_TOKEN=Your session has expired. Please log in again.
# User API Response Message
API.USER_FOUND_SUCCESS=User details found
# Spring Security
spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
